name: Maven Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch:      

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

#    - name: Run Super-Linter
#      uses: github/super-linter@v4
#      env: 
#        DEFAULT_BRANCH: master
#        VALIDATE_ALL_CODEBASE: true
#        GITHUB_TOKEN: ${{ secrets.VILAS_GITHUB_TOKEN }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
            
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      #uses: github/codeql-action/analyze@46a6823b81f2d7c67ddf123851eea88365bc8a67        
      uses: github/codeql-action/analyze@v2
      with:
        upload: False
        output: sarif-results
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # You can specify your desired Java version here
        distribution: 'temurin' #other option distribution: 'adopt' ref. https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
        
    - name: Build with Maven
      run: mvn clean install  # Replace with your actual Maven build command

    - name: Run Maven tests
      run: mvn test  # Run Maven tests
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Dockerize application
      run: |
        docker build -t ayush2023oct/ayuapp .
       
    - name: Login to Docker
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME}} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push to DockerHub
      run: docker push ayush2023oct/ayuapp  
      
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.7.0
      with:
       target: 'https://www.zaproxy.org/'
